import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

interface Report {
  id: string;
  created_at: string;
  platform_id: string;
  language: string;
  extracted_text: string;
  category: string;
  severity: number;
  risk_level: string;
  confidence: number;
  rationale: string;
  highlighted_phrases: string[];
  file_hash?: string;
}

export const generateEvidencePDF = (report: Report): PassThrough => {
  const doc = new PDFDocument({ margin: 50 });
  const stream = new PassThrough();
  
  doc.pipe(stream);

  // Title
  doc.fontSize(20).text('DIGITAL EVIDENCE DOCUMENTATION', { align: 'center' });
  doc.fontSize(12).text('Safenet.ai - Tamper-Evident Record', { align: 'center' });
  doc.moveDown(2);

  // Report Information
  doc.fontSize(14).text('Report Information', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10);
  doc.text(`Report ID: ${report.id.substring(0, 8)}...`);
  doc.text(`Created: ${new Date(report.created_at).toLocaleString()}`);
  doc.text(`Platform: ${report.platform_id.charAt(0).toUpperCase() + report.platform_id.slice(1)}`);
  doc.text(`Language: ${report.language === 'en' ? 'English' : 'Amharic'}`);
  if (report.file_hash) {
    doc.text(`SHA-256 Hash: ${report.file_hash.substring(0, 32)}...`);
  }
  doc.moveDown(2);

  // Classification Results
  doc.fontSize(14).text('Classification Results', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10);
  doc.text(`Category: ${report.category.replace(/_/g, ' ').toUpperCase()}`);
  doc.text(`Severity: ${report.severity}/100`);
  doc.text(`Risk Level: ${report.risk_level.toUpperCase()}`);
  doc.text(`Confidence: ${(report.confidence * 100).toFixed(1)}%`);
  doc.moveDown(2);

  // Analysis
  doc.fontSize(14).text('Analysis', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).text(report.rationale, { align: 'justify' });
  doc.moveDown(1);

  // Flagged Phrases
  if (report.highlighted_phrases && report.highlighted_phrases.length > 0) {
    doc.fontSize(12).text('Flagged Phrases:', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10);
    report.highlighted_phrases.forEach(phrase => {
      doc.text(`• ${phrase}`);
    });
    doc.moveDown(1);
  }

  // Extracted Content
  doc.fontSize(14).text('Extracted Content', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).text(report.extracted_text.substring(0, 2000), { align: 'justify' });
  doc.moveDown(2);

  // Footer
  doc.fontSize(8).text(
    `Generated by Safenet.ai on ${new Date().toISOString()}`,
    { align: 'center' }
  );

  doc.end();
  return stream;
};

export const generateComplaintPDF = (report: Report, language: string = 'en'): PassThrough => {
  const doc = new PDFDocument({ margin: 50 });
  const stream = new PassThrough();
  
  doc.pipe(stream);

  if (language === 'am') {
    // Amharic version
    doc.fontSize(16).text('የወንጀል ቅሬታ ማመልከቻ', { align: 'center' });
    doc.fontSize(12).text('የሳይበር ወንጀል ጥቆማ', { align: 'center' });
    doc.moveDown(2);
    
    doc.fontSize(10);
    doc.text(`ቀን: ${new Date(report.created_at).toLocaleDateString()}`);
    doc.text(`መድረክ: ${report.platform_id}`);
    doc.text(`የጥቃት ዓይነት: ${report.category}`);
    doc.moveDown(1);
    
    doc.text('ማስረጃ:');
    doc.text(report.extracted_text.substring(0, 1500));
  } else {
    // English version
    doc.fontSize(16).text('CRIMINAL COMPLAINT FORM', { align: 'center' });
    doc.fontSize(12).text('Cybercrime Report - Technology-Facilitated Gender-Based Violence', { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).text('TO: Federal Police Cyber Crime Investigation Unit');
    doc.moveDown(1);

    doc.fontSize(12).text('INCIDENT DETAILS', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10);
    doc.text(`Date of Incident: ${new Date(report.created_at).toLocaleDateString()}`);
    doc.text(`Platform: ${report.platform_id.charAt(0).toUpperCase() + report.platform_id.slice(1)}`);
    doc.text(`Type of Abuse: ${report.category.replace(/_/g, ' ').toUpperCase()}`);
    doc.text(`Severity Level: ${report.risk_level.toUpperCase()}`);
    doc.moveDown(1);

    doc.fontSize(12).text('APPLICABLE LAWS', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10);
    doc.text('• Proclamation No. 958/2016 - Computer Crime Proclamation');
    doc.text('  - Article 8: Criminal intimidation using computer');
    doc.text('  - Article 13: Dissemination of obscene content');
    doc.text('• Proclamation No. 1185/2020 - Hate Speech and Disinformation Prevention');
    doc.moveDown(1);

    doc.fontSize(12).text('EVIDENCE SUMMARY', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10);
    doc.text(`Analysis: ${report.rationale}`);
    doc.moveDown(0.5);
    doc.text('Content:');
    doc.text(report.extracted_text.substring(0, 1500), { align: 'justify' });
    doc.moveDown(2);

    doc.fontSize(12).text('FILING LOCATIONS', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(10);
    doc.text('1. Federal Police Cyber Crime Unit');
    doc.text('   Addis Ababa, Ethiopia | +251-111-572355');
    doc.text('2. Ministry of Women and Social Affairs');
    doc.text('   Addis Ababa, Ethiopia | +251-111-515179');
  }

  doc.moveDown(2);
  doc.fontSize(8).text(`Generated by Safenet.ai | ${new Date().toISOString()}`, { align: 'center' });

  doc.end();
  return stream;
};
