import type { Platform, Resource } from "./types"

export const PLATFORMS: Platform[] = [
  { id: "telegram", name: "Telegram", icon: "MessageCircle" },
  { id: "facebook", name: "Facebook", icon: "Facebook" },
  { id: "instagram", name: "Instagram", icon: "Instagram" },
  { id: "twitter", name: "Twitter/X", icon: "Twitter" },
  { id: "tiktok", name: "TikTok", icon: "Video" },
  { id: "whatsapp", name: "WhatsApp", icon: "Phone" },
  { id: "email", name: "Email", icon: "Mail" },
  { id: "sms", name: "SMS", icon: "MessageSquare" },
  { id: "other", name: "Other", icon: "Globe" },
]

export const RESOURCES: Resource[] = [
  {
    id: "1",
    name: "Ethiopian Women Lawyers Association",
    name_am: "የኢትዮጵያ ሴቶች ጠበቆች ማህበር",
    type: "legal_aid",
    phone: "+251-111-553777",
    email: "info@ewla-et.org",
    website: "https://ewla-et.org",
    region: "addis_ababa",
    description: "Free legal aid and counseling for women victims of violence",
    description_am: "ለጥቃት ሰለባ ሴቶች ነፃ የህግ እርዳታ እና ምክር",
  },
  {
    id: "2",
    name: "Association for Women's Sanctuary and Development",
    name_am: "የሴቶች መጠለያ እና ልማት ማህበር",
    type: "shelter",
    phone: "+251-111-572428",
    region: "addis_ababa",
    description: "Emergency shelter and rehabilitation for survivors",
    description_am: "ለተጎጂዎች የአደጋ ጊዜ መጠለያ እና መልሶ ማቋቋም",
  },
  {
    id: "3",
    name: "National GBV Hotline",
    name_am: "ብሔራዊ የጾታ ጥቃት ስልክ መስመር",
    type: "helpline",
    phone: "8383",
    region: "nationwide",
    description: "24/7 confidential support hotline",
    description_am: "24/7 ሚስጥራዊ የድጋፍ ስልክ መስመር",
  },
  {
    id: "4",
    name: "Network of Ethiopian Women's Association",
    name_am: "የኢትዮጵያ ሴቶች ማህበራት ኔትወርክ",
    type: "ngo",
    phone: "+251-111-553719",
    website: "https://newa-et.org",
    region: "addis_ababa",
    description: "Advocacy and support for women's rights",
    description_am: "ለሴቶች መብት ጥብቅና እና ድጋፍ",
  },
  {
    id: "5",
    name: "Oromia Women's Association",
    name_am: "የኦሮሚያ ሴቶች ማህበር",
    type: "ngo",
    phone: "+251-115-515414",
    region: "oromia",
    description: "Support services for women in Oromia region",
    description_am: "በኦሮሚያ ክልል ለሚገኙ ሴቶች የድጋፍ አገልግሎቶች",
  },
]

export const REGIONS = [
  { id: "nationwide", name: "Nationwide", name_am: "በአገር አቀፍ" },
  { id: "addis_ababa", name: "Addis Ababa", name_am: "አዲስ አበባ" },
  { id: "oromia", name: "Oromia", name_am: "ኦሮሚያ" },
  { id: "amhara", name: "Amhara", name_am: "አማራ" },
  { id: "tigray", name: "Tigray", name_am: "ትግራይ" },
  { id: "snnpr", name: "SNNPR", name_am: "ደቡብ ብሔሮች" },
]

export const THREAT_KEYWORDS = [
  "kill",
  "murder",
  "die",
  "death",
  "attack",
  "hurt",
  "harm",
  "destroy",
  "burn",
  "rape",
  "assault",
  "beat",
  "stab",
  "shoot",
  "bomb",
  "ግደል",
  "ሞት",
  "አጥፋ",
  "አቃጥል",
  "ደፈረ",
  "ደበደበ",
]

export const STALKING_INDICATORS = [
  "watching you",
  "following",
  "know where you live",
  "saw you at",
  "tracking",
  "monitoring",
  "your location",
  "your address",
  "እከታተልሻለሁ",
  "አውቃለሁ የት እንደምትኖሪ",
]
